### ISSUE TITLE
Handling terminated instances

### ISSUE THREAD

**Issue by imduffy15** [thigley986/Lambda-AWS-Automated-Alarm-Creation#2]
How are you handling cleaning up after instances are terminated? Aren't you left with a bunch of insufficient data status' on alarms?

**Comment by thigley986** [comment]
I've posted the [cleanup script](https://github.com/thigley986/Lambda-AWS-Automated-Alarm-Cleanup/blob/master/Alarm_Cleanup.py) we run as a complement to this alarm creation script.

**Comment by imduffy15** [comment]
Awesome! Thank you @thigley986 some awesome work here, really love this idea.

It would be really cool to create a CloudWatch Event [1] for monitoring new and terminated instance to trigger the lambda function to create/delete all the associated alarms. https://aws.amazon.com/blogs/apn/automatically-delete-terminated-instances-in-chef-server-with-aws-lambda-and-cloudwatch-events/ kind of describes it. If I end up taking a stab at doing this I'll share what I end up with. 

[1] https://aws.amazon.com/blogs/aws/new-cloudwatch-events-track-and-respond-to-changes-to-your-aws-resources/
